project13/urls.py
from django.contrib import admin
from django.urls import path,include
from generic.views import *
import specific

urlpatterns = [
    path('admin/', admin.site.urls),
    path('father/',father,name='father'),
    path('mother/',mother,name='mother'),
    path('specific/',include('specific.urls')),
]

specific/urls.py
from specific.views import *
from django.urls import path
app_name='specific'
urlpatterns=[
    path('child1/',child1,name='child1'),
    path('child2/',child2,name='child2'),
]

generic/models.py
from django.db import models

# Create your models here.

specific/models.py
from django.db import models

# Create your models here.

generic/views.py
from django.shortcuts import render

# Create your views here.
def father(request):
    return render(request,'father.html')

def mother(request):
    return render(request,'mother.html')
    

specific/views.py
from django.shortcuts import render

# Create your views here.
def child1(request):
    return render(request,'child1.html')
def child2(request):
    return render(request,'child2.html')

templates/child1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>hii sis..</h1>
        <a href="{% url 'specific:child2' %}"><h2>response from child2</h2></h1></a>
    </center>
</body>
</html>

templates/child2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>hii akkaa..</h1>
       
    </center>
</body>
</html>

templates/father.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>hiii..</h1>
        <a href="{% url 'mother' %}"><h2>response from mother</h2></a>
        <a href="{% url 'father' %}"><h2>response from father</h2></a>
        <a href="{% url 'specific:child1' %}"><h2>response from child1</h2></a>
        <a href="{% url 'specific:child2' %}"><h2>response from child2</h2></h1></a>
    </center>
</body>
</html>

templates/mother.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>helloo..</h1>
        
    </center>
</body>
</html>